require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubtopicsController do

  # This should return the minimal set of attributes required to create a valid
  # Subtopic. As you add validations to Subtopic, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubtopicsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all subtopics as @subtopics" do
      subtopic = Subtopic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:subtopics).should eq([subtopic])
    end
  end

  describe "GET show" do
    it "assigns the requested subtopic as @subtopic" do
      subtopic = Subtopic.create! valid_attributes
      get :show, {:id => subtopic.to_param}, valid_session
      assigns(:subtopic).should eq(subtopic)
    end
  end

  describe "GET new" do
    it "assigns a new subtopic as @subtopic" do
      get :new, {}, valid_session
      assigns(:subtopic).should be_a_new(Subtopic)
    end
  end

  describe "GET edit" do
    it "assigns the requested subtopic as @subtopic" do
      subtopic = Subtopic.create! valid_attributes
      get :edit, {:id => subtopic.to_param}, valid_session
      assigns(:subtopic).should eq(subtopic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Subtopic" do
        expect {
          post :create, {:subtopic => valid_attributes}, valid_session
        }.to change(Subtopic, :count).by(1)
      end

      it "assigns a newly created subtopic as @subtopic" do
        post :create, {:subtopic => valid_attributes}, valid_session
        assigns(:subtopic).should be_a(Subtopic)
        assigns(:subtopic).should be_persisted
      end

      it "redirects to the created subtopic" do
        post :create, {:subtopic => valid_attributes}, valid_session
        response.should redirect_to(Subtopic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved subtopic as @subtopic" do
        # Trigger the behavior that occurs when invalid params are submitted
        Subtopic.any_instance.stub(:save).and_return(false)
        post :create, {:subtopic => {}}, valid_session
        assigns(:subtopic).should be_a_new(Subtopic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Subtopic.any_instance.stub(:save).and_return(false)
        post :create, {:subtopic => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested subtopic" do
        subtopic = Subtopic.create! valid_attributes
        # Assuming there are no other subtopics in the database, this
        # specifies that the Subtopic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Subtopic.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => subtopic.to_param, :subtopic => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested subtopic as @subtopic" do
        subtopic = Subtopic.create! valid_attributes
        put :update, {:id => subtopic.to_param, :subtopic => valid_attributes}, valid_session
        assigns(:subtopic).should eq(subtopic)
      end

      it "redirects to the subtopic" do
        subtopic = Subtopic.create! valid_attributes
        put :update, {:id => subtopic.to_param, :subtopic => valid_attributes}, valid_session
        response.should redirect_to(subtopic)
      end
    end

    describe "with invalid params" do
      it "assigns the subtopic as @subtopic" do
        subtopic = Subtopic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Subtopic.any_instance.stub(:save).and_return(false)
        put :update, {:id => subtopic.to_param, :subtopic => {}}, valid_session
        assigns(:subtopic).should eq(subtopic)
      end

      it "re-renders the 'edit' template" do
        subtopic = Subtopic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Subtopic.any_instance.stub(:save).and_return(false)
        put :update, {:id => subtopic.to_param, :subtopic => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested subtopic" do
      subtopic = Subtopic.create! valid_attributes
      expect {
        delete :destroy, {:id => subtopic.to_param}, valid_session
      }.to change(Subtopic, :count).by(-1)
    end

    it "redirects to the subtopics list" do
      subtopic = Subtopic.create! valid_attributes
      delete :destroy, {:id => subtopic.to_param}, valid_session
      response.should redirect_to(subtopics_url)
    end
  end

end
